config/routes.rb
require "sidekiq/web"

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(username),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:username]),
  ) & ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:password]),
  )
end

flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
  builder.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:username]),
    ) & ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:password]),
    )
  end
end

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :users do
      member do
        get :send_beta_invitation
      end
    end
    resources :modes
    resources :buttons
    resources :events

    root to: "users#index"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }

  mount Sidekiq::Web => "/admin/sidekiq"

  mount flipper_app, at: "/flipper"

  resource :software_button, only: %i[new create]
  resources :buttons, only: %i[show edit update] do
    member do
      get :report
      post :event
      get :all_my_buttons
      get :mode_report
    end
  end
  # resource :home do
  #   member do
  #     get :build
  #     get :server
  #   end
  # end
  get "/quotes/sample", to: "quotes#sample"
  get "/home/build", to: "home#build"
  get "/home/server", to: "home#server"

  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  post "/", to: "buttons#create"
  patch "/", to: "buttons#update"
  resources :home, only: [:index] do
    collection do
      get :old_index
      get :enable_flip
      get :disable_flip
    end
  end
  root to: "home#index"
end

app/models/button.rb
class Button < ApplicationRecord
  attr_accessor :ssid, :password

  validates :email, :site, :external_reference, presence: true

  has_many :events, dependent: :delete_all

  def to_s
    external_reference
  end

  def daily_events
    events.order("date(created_at) DESC").group("date(created_at)").count
  end

  def report(report_name)
    send(report_name) if report_name
  end

  def counter_activity_time_tracker
    {
      morning_events: slot_time_events_day(6, 14),
      day_events: slot_time_events_day(14, 22),
      night_events: slot_time_events_night(22, 6),
    }
  end

  private

  def slot_time_events_night(start_hour, end_hour)
    events.count { |s| s.created_at.hour >= start_hour || s.created_at.hour < end_hour }
  end

  def slot_time_events_day(start_hour, end_hour)
    events.count { |s| s.created_at.hour >= start_hour && s.created_at.hour < end_hour }
  end

  def total_count
    events.count
  end

  def activity_by_day
    {
      activity: activity,
      months: activity_by_day_dates.map { |date| date.strftime("%b") }.uniq,
    }
  end

  def activity_by_day_dates
    start_date = (Time.zone.today - 60.days).beginning_of_week(:sunday)
    (start_date..Time.zone.today).to_a
  end

  def bucket
    max = daily_events.values.max.to_i
    (max / 3) + 1
  end

  def activity
    actual_activity = daily_events.map { |date, value| [date, value] }.to_h
    activity_by_day_dates.map do |date|
      [
        date.to_s,
        actual_activity[date] &&
          (actual_activity[date].to_i / bucket) + 1,
        actual_activity[date].to_i,
      ]
    end
  end
end

app/controllers/admin/buttons_controller.rb
module Admin
  class ButtonsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    @button = Button.new(button_params)
    @button.save!
    UserMailer.with(button: @button).button_registration.deliver_later
    render json: {button_url: button_url(@button)}, status: :created
  rescue ActiveRecord::RecordInvalid => e
    render json: {error: e.message}, status: :unprocessable_entity
  end

  def show
    @button = Button.find(params[:id])
  end

  def event
    @button = Button.find(params[:id])
    @button.events.create
  end

  def report
    @button = Button.find(params[:id])
    @total_events_count = @button.events.count
    @events = @button.events.page params[:page]
  end

  def mode_report
    @button = Button.find(params[:id])
    # @reports = @button.mode.properties["reports"].create_report # which will
    @mode = Mode.first
    @reports = @mode.properties["reports"]
    @data = @mode.properties["dataGeneratorMethod"]
  end

  def edit
    @button = Button.find(params[:id])
  end

  def update
    @button = Button.find(params[:id])
    @button.update(button_params) ? (redirect_to button_path(@button)) : (render :new)
  end

  def all_my_buttons
    @button = Button.find(params[:id])
    @buttons = Button.where(email: @button.email)
  end

  private

  def button_params
    return unless params[:button]

    params.require(:button).permit(:email, :site, :external_reference, :name)
  end
end

app/views/buttons/all_my_buttons.html.erb
<h3>All My Buttons</h3>
<section data-testid="buttons">
<div class="d-flex justify-content-around flex-wrap">
    <% @buttons.each do |button| %>
    <div class="card col-12 col-md-4 col-lg-3 m-2" style="min-width: 28rem;">
      <div class="card-body">
        <h5 class="card-title">ID: <%= button.id.slice(0,6) %></h5>
        <p class="card-text">External Ref.: <%= button.external_reference %></p>
        <%= link_to button.id.slice(0,6),
         button_path(button), class: "button-link btn btn-primary", style: "width:100%" %>
      </div>
    </div>
    <% end %>
</div>

app/views/buttons/edit.html.erb
<h1>Button is: <%= @button %></h1>
<p>B created at:<%= @button.created_at %></p>
<p>B name: <%= @button.name %></p>


<%= form_with model: @button, url: button_path, data: {testid: "update_name_form"} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="timezone">Timezone</label>
        <%= select_tag(
        "timezone",
        options_for_select([nil, *ActiveSupport::TimeZone.all.map(&:name)]),
        class: "form-control"
        ) 
    %>
  </div>
  <div class="form-group">
    <label for="mode">Mode</label>
    <%= select_tag(
        "mode",
        options_for_select([nil, *Mode.all.pluck(:name)]),
        class: "form-control",
        ) 
    %>
  </div>


  <%= f.submit(
    "update name".to_s,
    class: "btn btn-primary form-control",
    data: {
      "disable-with": '<i class="fa fa-spinner fa-spin"></i>',
          }) %>
<% end %>

app/views/buttons/events.html.erb
<h1>Events for <%= @button.external_reference %></h1>

<ul class="list-group">
<% @events.each_with_index do |event, index| %>
  <li class="list-group-item">
  <div class="row">
  <div class="col-2">
  <%= index %>
  </div>
  <div class="col-6">
  <%= event.created_at %>
  </div>
    </div>
  </li>
<% end %>
</ul>

app/views/buttons/mode_report.erb
<h1><%= @mode.name %></h1>

<div class="d-flex flex-wrap row">
  <% @reports.each do |report| %>
    <div class="col-12 col-lg-6">
      <div class="card my-1">
        <div class="card-body m-1">
          <%= render(
            partial: File.join("reports", report["template"]),
            locals: {
              report: @button.report(report["report_generator"])
            }
           ) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/buttons/report.html.erb
<h1>Report for button <%= @button %></h1>
<section data-testid="report">
  <h4 data-testid="report-total"><%= @total_events_count %> total events have been recorded</h4>
  <ul class="list-group" data-testid="report-daily-total">
    <% @button.daily_events.each do |day, count| %>
    <li class="list-group-item">
      <%= day %>:  <%=  count %>
    </li>
    <% end %>
  </ul>
  <%= content_tag :div,
    id: "button-report",
    data: @button.daily_events.map { |date, value| [date.strftime('%Q').to_i, value] }.to_json do %>
  <% end %>
  <%= javascript_pack_tag 'button_report' %>
  <%= content_tag :div,
    id: "button-raw-report",
    data: @button.events.map { |event| [event.created_at.to_datetime.strftime('%Q').to_i, 1] }.to_json do %>
  <% end %>
  <%= javascript_pack_tag 'button_raw_report' %>
</section>

<h3>All Events</h3>
<section data-testid="events">
  <% if @events.empty? %>
    <p>this button has not yet been pressed</p>
  <% else %>
  <ul class="list-group">
    <% @events.each do |event| %>
      <li class="list-group-item">
        <%= event.created_at %>
      </li>
    <% end %>
  </ul>
  <% end %>
  <%= paginate @events %>
</section>

app/views/buttons/show.html.erb
<h1>Button <%= @button %></h1>
<h3>Your Button's name:</h3><section data-testid="button-name"><h4> <%= @button.name %></h4> </section>
<div data-testid="button-actions" class="d-flex justify-content-between flex-wrap">
  <div class="col-12 col-md-4 col-lg-3">
    <%= link_to "Configure button", edit_button_path(@button), class: "btn btn-secondary btn-block mb-2" %>
  </div>
  <div class="col-12 col-md-4 col-lg-3">
    <%= link_to "All my buttons", all_my_buttons_button_path(@button), class: "btn btn-secondary btn-block mb-2" %>
  </div>
  <div class="col-12 col-md-4 col-lg-3">
    <%= link_to "raw report", report_button_path(@button), class: "btn btn-secondary btn-block mb-2" %>
  </div>
  <div class="col-12 col-md-4 col-lg-3">
    <%= link_to "mode report", mode_report_button_path(@button), class: "btn btn-secondary btn-block mb-2" %>
  </div>
</div>


<section data-testid="software-button">
  <div class="col-12">
  <button
    class="btn btn-primary btn-block btn-huge btn-high-viz-action"
    onClick="this.disabled = true; fetch('<%= event_button_path(@button) %>', { method: 'POST' }).then(() => this.disabled = false)",
  >Button</button>
  </div
</section>