config/routes.rb
require "sidekiq/web"

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(username),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:username]),
  ) & ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:password]),
  )
end

flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
  builder.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:username]),
    ) & ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:password]),
    )
  end
end

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :users do
      member do
        get :send_beta_invitation
      end
    end
    resources :modes
    resources :buttons
    resources :events

    root to: "users#index"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }

  mount Sidekiq::Web => "/admin/sidekiq"

  mount flipper_app, at: "/flipper"

  resource :software_button, only: %i[new create]
  resources :buttons, only: %i[show edit update] do
    member do
      get :report
      post :event
      get :all_my_buttons
      get :mode_report
    end
  end
  # resource :home do
  #   member do
  #     get :build
  #     get :server
  #   end
  # end
  get "/quotes/sample", to: "quotes#sample"
  get "/home/build", to: "home#build"
  get "/home/server", to: "home#server"

  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  post "/", to: "buttons#create"
  patch "/", to: "buttons#update"
  resources :home, only: [:index] do
    collection do
      get :old_index
      get :enable_flip
      get :disable_flip
    end
  end
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    temp_password = SecureRandom.hex(8)

    @user = User.new(password: temp_password, password_confirmation: temp_password)
  end

  def old_index
  end

  # TODO: move to own controller or check if flipper provides this already?
  def enable_flip
    begin
      unless signed_in?
        user = User.with_reset_password_token(params[:reset_token])
        sign_in user
      end
      jwt_payload = JWT.decode(params[:token], Rails.application.secrets.secret_key_base).first
      current_user_id = jwt_payload["id"]
      # TODO: the feature flip should be passed in the jwt payload
      Flipper[:beta_button].enable current_user if current_user && current_user.id == current_user_id
      flash[:success] = "Congratulations you are now part of the Button Beta."
    rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
      # head :unauthorized
    end
    redirect_to root_path
  end

  # TODO: move to own controller or check if flipper provides this already?
  def disable_flip
    # TODO: force a login
    begin
      jwt_payload = JWT.decode(params[:token], Rails.application.secrets.secret_key_base).first
      current_user_id = jwt_payload["id"]
      Flipper[:beta_button].disable current_user if current_user && current_user.id == current_user_id
    rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
      # head :unauthorized
    end
    redirect_to root_path
  end
end

app/views/home/_demo_button.html.erb
<div data-testid="demo-button">
  <div class="active" data-testid="mode-reflex">reflex</div>
  <div data-testid="mode-timer">timer</div>
  <div data-testid="mode-counter">counter</div>
  <button class="btn btn-primary" >button</button>
  <div data-testid="message">reflex test started</div>
</div>

app/views/home/build.html.erb
<div>
  <div class="container text-center">
    <h1>Build the hardware button</h1>
  </div>
</div>


10 step instruction goes here :)

app/views/home/index.html.erb
<% content_for :pre_container do %>
  <div class="jumbotron bg-secondary text-white">
    <div class="container">
      <div>
        <h1 class="display-text stronger">Remote Button</h1>
      </div>
      <p class="display-text">
        Press the internet wherever you are
      </p>
      <div>
      <%= link_to 'Sign up for free', new_user_registration_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<% if Flipper.enabled?(:b_e_n_s_a_y_s) %>
  <p style="font-size: 10em">
    B E N S A Y S
  </p>
<% end %>

<section data-testid="demo-section">
  <div class="card">
    <div class="card-header" data-testid="title">
      Demo software button
    </div>
    <div class="card-body">
      <%= content_tag(
        :div,
        "",
        data: {
          app: "demo-button-app",
          config: {
            title: "Demo Button App",
            demoButtonId: System::DemoButton::TEMPLATES[:demo_button][:id]
          }.to_json,
        }
      )%>
      <%= javascript_pack_tag "demo_button_app" %>
    </div>
    <div class="card-footer" data-testid="footer">
      Note: other users may be interacting with this same button and affect the outcome.
    </div>
  </div>
</section>

<% if Flipper.enabled?(:beta_button, current_user) %>
  <div class="col-md-6 mx-auto">
    <p style="font-size: 4em">
      Congratulations!
    </p>
    <p class="center-text">
      <strong>
        you are part of the Beta
      </strong>
    </p>
    <p>
      <i>more information coming your way soon</i>
    </p>
  </div>
<% else %>
  <div class="col-md-6 mx-auto">
    <p>
      <i>Sorry not part of beta yet</i>
    </p>
  </div>
<% end %>

<% if signed_in? %>
  <!-- content for siged in users -->
  <p>We hope you will shortly be accepted into our beta program</p>
<% else %>
  <div class="col-md-6 mx-auto">
    <%= form_for(@user, url: registration_path(@user)) do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>

    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, class: "form-control", autocomplete: "email" %>
    </div>

    <%= f.hidden_field :password, autocomplete: "new-password" %>

    <%= f.hidden_field :password_confirmation, autocomplete: "new-password" %>

    <div class="actions">
      <%= f.submit "Sign up", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/home/old_index.html.erb
<div class="banner">
  <div class="container text-center">
          <div class="container-esp32">
        <div class="card-esp32">
            <div class="esp32">
                <div class="circle"></div>
                <%= image_tag(
                              "arduino-esp32.png",
                              size: "50x50",
                              alt: "Arduino ESP-32"
                              ) %>
            </div>
            <div class="info">
                <h1 class="title">Dynamic Button</h1>
                <h3>More to the button than meets the eye</h3>
            </div>
        </div>
    </div>
      <a class="btn-cta" target="_blank" href="https://github.com/failure-driven/remote-button" role="button">find out more</a>
    
    <!-- <p><span id="banner-typed-text"></span></p> -->
  </div>
</div>

<section id="process" class="process">
  <div class="container container-fluid container-fluid-max">
    <div class="row text-center">
    VIDEO GOES HERE
    </div>
  </div>
</section>

<section id="process" class="process">
  <div class="container container-fluid container-fluid-max">
    <div class="row text-center">
      <div class="col-12 col-sm-12 col-lg-3">
        <%= link_to home_build_path do %>
          <div class="card">Build the IoT Button</div>
        <% end %>
        the IoT remote button is based on a few simple components of a ESP32 (Arduino like WiFi connected board), a push button and an RGB LED (Red Green Blue Light Emitting diode)
      </div>
      <div class="col-12 col-sm-12 col-lg-3">
        <%= link_to home_server_path do %>
          <div class="card">Deploy the server</div>
        <% end %>
        Simple to deploy your own version on a serivce like AWS EC2 or Heroku, or connect to our server at ... herokuaddress
      </div>
      <div class="col-12 col-sm-12 col-lg-3">
        <div class="card">Try it now
        </div>
        software button version
      </div>
    </div>
  </div>
</section>
<section id="process" class="process">
  <div class="container container-fluid container-fluid-max">
    <div class="row text-center">
      <div class="col-12 mt-5">
        <h2>What is a remote button?</h2>
      </div>

      <div class="col-12 col-sm-12 col-lg-3">
        <div class="card">Hardware</div>
      </div>
      <div class="col-12 col-sm-12 col-lg-3">
        <div class="card">Get the code
        </div>
      </div>
      <div class="col-12 col-sm-12 col-lg-3">
      <div class="card">Multitude of uses
      </div>
      </div>
      <div class="col-12 col-sm-12 col-lg-3">
        <div class="card">Connect with friends</div>
      </div>
      <div class="col-12 pt-3">
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container-fluid container-fluid-max">
    <div class="row text-center">
      <div class="col-12 pt-3">
        Why not try a software version of the button NOW!
      </div>
      <div class="col-12 pt-3">
        <%= link_to( "Software Button",
          new_software_button_path,
          class: "btn-cta",
          data: {
            testid: "try-software-button-action",
          }
        )%>
      </div>
    </div>
  </div>
</section>

<div class="process-card container text-center">
  <h2 class="mt-5 mb-5">
    How it Works
  </h2>
  <div class="row">

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
      <%= image_tag(
          "unbox.png",
          size: "50x50",
          alt: "unboxing",
          data: {
            testid: "inboxing-image"
          }
          ) %>
      <h3>Unbox</h3>
      <p>Recieve your button in the mail</p>
    </div>

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
            <%= image_tag(
          "configure.png",
          size: "50x50",
          alt: "configure",
          data: {
            testid: "configure-image"
          }
          ) %>
      <h3>Setup</h3>
      <p>Connect your button to wifi</p>
    </div>

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
          <%= image_tag(
          "wait.png",
          size: "50x50",
          alt: "configuring button",
          data: {
            testid: "configure-button-image"
          }
          ) %>
      <h3>Configure</h3>
      <p>Customize the mode that you wish to use.</p>
    </div>

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
      <%= image_tag(
          "email.png",
          size: "50x50",
          alt: "register email",
          data: {
            testid: "reg-email-image"
          }
          ) %>
      <h3>Register Your Email</h3>
      <p>Access your button HERE</p>
    </div>

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
      <%= image_tag(
          "email.png",
          size: "50x50",
          alt: "register email",
          data: {
            testid: "reg-email-image"
          }
          ) %>
      <h3>Configure Button Setup</h3>
      <p>Choose a name for your button so you can identify it, select a mode. If your registration is successful, your button will flash (x) times.</p>
    </div>

    <div class="col-12 col-sm-12 col-lg-3 mb-3">
      <%= image_tag(
          "on.png",
          size: "50x50",
          alt: "on button",
          data: {
            testid: "activated-button-image"
          }
          ) %>
     <h3>You are ready to go!</h3>
    </div>

  </div>
</div>

app/views/home/server.html.erb
<div>
  <div class="container text-center">
    <h1>How to deploy to the server</h1>
  </div>
</div>


10 step instruction goes here :)