config/routes.rb
require "sidekiq/web"

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(username),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:username]),
  ) & ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:password]),
  )
end

flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
  builder.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:username]),
    ) & ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:password]),
    )
  end
end

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :users do
      member do
        get :send_beta_invitation
      end
    end
    resources :modes
    resources :buttons
    resources :events

    root to: "users#index"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }

  mount Sidekiq::Web => "/admin/sidekiq"

  mount flipper_app, at: "/flipper"

  resource :software_button, only: %i[new create]
  resources :buttons, only: %i[show edit update] do
    member do
      get :report
      post :event
      get :all_my_buttons
      get :mode_report
    end
  end
  # resource :home do
  #   member do
  #     get :build
  #     get :server
  #   end
  # end
  get "/quotes/sample", to: "quotes#sample"
  get "/home/build", to: "home#build"
  get "/home/server", to: "home#server"

  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  post "/", to: "buttons#create"
  patch "/", to: "buttons#update"
  resources :home, only: [:index] do
    collection do
      get :old_index
      get :enable_flip
      get :disable_flip
    end
  end
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable, :trackable
  def flipper_id
    id
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    def send_beta_invitation
      # TODO: add a one time token for signin as well
      UserMailer
        .with(
          user: requested_resource,
          reset_token: requested_resource.send(:set_reset_password_token),
          token: generate_jwt_token_for(requested_resource),
        )
        .user_beta_invitation
        .deliver_now # .deliver_later not working in test
      redirect_to admin_user_path(requested_resource)
    end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    private

    def generate_jwt_token_for(resource)
      JWT.encode({
        id: resource.id,
        exp: 1.day.from_now.to_i,
      }, Rails.application.secrets.secret_key_base,)
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController # rubocop:disable Style/ClassAndModuleChildren
  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super do |resource|
      sign_in resource
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::PasswordsController
  def auth
    user = User.where("id =? and reset_password_token =?", params[:format], params[:reset_password_token]).first
    binding.pry
    if user.present?
      user.reset_password_token = nil
      user.save
      sign_in user
      redirect_to root_path, notice: "success??"#Login path
    else
      redirect_to root_path, notice: "no user??"
    end
  end
end

app/views/admin/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: page.resource.class.human_attribute_name(attribute.name),
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>

<div class="form-actions">
  <div style="margin-bottom: 1.5rem;">
    <%= link_to "Send Beta Invitation Email", send_beta_invitation_admin_user_path(page.resource), class: "button" %>
  </div>
</div>