config/routes.rb
require "sidekiq/web"

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(username),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:username]),
  ) & ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(Rails.application.credentials.sidekiq[:password]),
  )
end

flipper_app = Flipper::UI.app(Flipper.instance) do |builder|
  builder.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:username]),
    ) & ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(Rails.application.credentials.flipper[:password]),
    )
  end
end

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :users do
      member do
        get :send_beta_invitation
      end
    end
    resources :modes
    resources :buttons
    resources :events

    root to: "users#index"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }

  mount Sidekiq::Web => "/admin/sidekiq"

  mount flipper_app, at: "/flipper"

  resource :software_button, only: %i[new create]
  resources :buttons, only: %i[show edit update] do
    member do
      get :report
      post :event
      get :all_my_buttons
      get :mode_report
    end
  end
  # resource :home do
  #   member do
  #     get :build
  #     get :server
  #   end
  # end
  get "/quotes/sample", to: "quotes#sample"
  get "/home/build", to: "home#build"
  get "/home/server", to: "home#server"

  get "test_root", to: "rails/welcome#index", as: "test_root_rails"

  post "/", to: "buttons#create"
  patch "/", to: "buttons#update"
  resources :home, only: [:index] do
    collection do
      get :old_index
      get :enable_flip
      get :disable_flip
    end
  end
  root to: "home#index"
end

app/views/layouts/_email_safe_button.html.erb
<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
  <tbody>
    <tr>
      <td align="<%= align %>">
        <table role="presentation" border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td><a href="<%= href %>" target="_blank"><%= label %></a></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer pb-3 d-flex justify-content-between">
  <ul class="nav">
    <li class="nav-link">
      © 2021 Remote Button Team
    </li>
    <%# <li class="nav-link">
      <a href="#">
        Contact Us
      </a>
    </li>
    <li class="nav-link">
      <a href="#">
        About Us
      </a>
    </li>
    <li class="nav-link">
      <a href="#">
        Terms
      </a>
    </li>
    <li class="nav-link">
      <a href="#">
        Privacy
      </a>
    </li>
    <li class="nav-link">
      <a href="#">
        Site Map
      </a>
    </li> %>
  </ul>
  <ul class="nav">
    <li class="nav-link" target="_blank">
      <a href="https://github.com/failure-driven/remote-button">
        <i class="fab fa-github"></i>
      </a>
    </li>
  </ul>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag(
            "remote_button_drawn_01.png",
            size: "50x50",
            alt: "Remote Button",
            data: {
              testid: "remote-button-image"
            }
            ) %>
  </a>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if signed_in? && current_user %>
        <a class="nav-item nav-link active" href="#">Register <span class="sr-only">(current)</span></a>
        <%= link_to home_build_path, class: "nav-item nav-link" do %>
          Build
        <% end %>
        <%= link_to home_server_path, class: "nav-item nav-link" do %>
          Server
        <% end %>
        <a class="nav-item nav-link" href="#">Guide</a>
        <a class="nav-item nav-link" href="#">Contact</a>
        <% if @button && !@button.new_record? %>
          <a class="nav-item nav-link" href="<%= button_path(@button) %>">Button</a>
        <% end %>
      <% end %>
      <% if @button && !@button.new_record? %>
        <a class="nav-item nav-link" href="<%= button_path(@button) %>">
          Button
        </a>
      <% end %>
    </div>
  </div>

  <ul class="navbar-nav ml-auto" style="flex-direction: row;">
    <% if signed_in? %>
      <li class="mt-2">
        <span class="nav-link">
          <%= current_user.email %>
        </span>
      </li>
      <li class="nav-link">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
      </li>
    <% else %>
      <li class="nav-link">
        <%= link_to 'Log in', new_user_session_path, class: "btn" %>
      </li>
      <li class="nav-link">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>

  <% if signed_in? && current_user %>
    <button class="navbar-toggler ml-3" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="" data-oldclass="navbar-toggler-icon">
        <%= image_tag(
                "on.png",
                size: "30x30",
                alt: "placeholder for menu bar",
                data: {
                  testid: "placeholder-image"
                }
                ) %>
      </span>
    </button>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoteButton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: "layouts/nav" %>

    <%= flash_messages %>

    <div class="pre-container">
      <%= yield :pre_container %>
    </div>

    <main class="container-fluid container">
      <%= yield %>
    </main>

    <%= render partial: "layouts/footer" %>

  </body>
</html>